# Generated by Django 3.2.3 on 2021-05-24 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, default='', verbose_name='Сообщение')),
                ('sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('recipient',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_messages',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_messages',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='BanUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banusers',
                                           to=settings.AUTH_USER_MODEL, verbose_name='Заблокированный пользователь')),
            ],
        ),
    ]
